from . import ast_nodes as ast_nodes
from absl.testing import absltest

class AstNodesTest(absltest.TestCase):
    def test_value_type(self) -> None: ...
    def test_pointer_type(self) -> None: ...
    def test_array_type(self) -> None: ...
    def test_complex_type(self) -> None: ...
    def test_struct_decl(self) -> None: ...
    def test_anonymous_struct_decl(self) -> None: ...
    def test_anonymous_union_decl(self) -> None: ...
