from . import enums as enums
from absl.testing import absltest

class EnumsTest(absltest.TestCase):
    def test_mjtJoint(self) -> None: ...
    def test_mjtEnableBit(self) -> None: ...
    def test_mjtGeom(self) -> None: ...
