from . import ast_nodes as ast_nodes, structs as structs, type_parsing as type_parsing
from absl.testing import absltest

class StructsTest(absltest.TestCase):
    def test_mjData(self) -> None: ...
    def test_mjVisual(self) -> None: ...
    def test_mjuiItem(self) -> None: ...
