def get_mjcb_act_bias() -> object: ...
def get_mjcb_act_dyn() -> object: ...
def get_mjcb_act_gain() -> object: ...
def get_mjcb_contactfilter() -> object: ...
def get_mjcb_control() -> object: ...
def get_mjcb_passive() -> object: ...
def get_mjcb_sensor() -> object: ...
def get_mjcb_time() -> object: ...
def get_mju_user_free() -> object: ...
def get_mju_user_malloc() -> object: ...
def get_mju_user_warning() -> object: ...
def set_mjcb_act_bias(arg0: object) -> None: ...
def set_mjcb_act_dyn(arg0: object) -> None: ...
def set_mjcb_act_gain(arg0: object) -> None: ...
def set_mjcb_contactfilter(arg0: object) -> None: ...
def set_mjcb_control(arg0: object) -> None: ...
def set_mjcb_passive(arg0: object) -> None: ...
def set_mjcb_sensor(arg0: object) -> None: ...
def set_mjcb_time(arg0: object) -> None: ...
def set_mju_user_free(arg0: object) -> None: ...
def set_mju_user_malloc(arg0: object) -> None: ...
def set_mju_user_warning(arg0: object) -> None: ...
