mjDISABLESTRING: tuple
mjENABLESTRING: tuple
mjFRAMESTRING: tuple
mjLABELSTRING: tuple
mjMAXCONPAIR: int
mjMAXIMP: float
mjMAXLIGHT: int
mjMAXLINE: int
mjMAXLINEPNT: int
mjMAXOVERLAY: int
mjMAXPLANEGRID: int
mjMAXVAL: float
mjMAXVFS: int
mjMAXVFSNAME: int
mjMINIMP: float
mjMINMU: float
mjMINVAL: float
mjNBIAS: int
mjNDYN: int
mjNEQDATA: int
mjNGAIN: int
mjNGROUP: int
mjNIMP: int
mjNREF: int
mjNSOLVER: int
mjPI: float
mjRNDSTRING: tuple
mjTIMERSTRING: tuple
mjVERSION_HEADER: int
mjVISSTRING: tuple
