import numpy as np
from mujoco import _structs, gl_context as gl_context

class Renderer:
    def __init__(self, model: _structs.MjModel, height: int = 240, width: int = 320, max_geom: int = 10000) -> None: ...
    @property
    def model(self): ...
    @property
    def scene(self) -> _structs.MjvScene: ...
    @property
    def height(self): ...
    @property
    def width(self): ...
    def enable_depth_rendering(self) -> None: ...
    def disable_depth_rendering(self) -> None: ...
    def enable_segmentation_rendering(self) -> None: ...
    def disable_segmentation_rendering(self) -> None: ...
    def render(self, *, out: np.ndarray | None = None) -> np.ndarray: ...
    def update_scene(self, data: _structs.MjData, camera: int | str | _structs.MjvCamera = -1, scene_option: _structs.MjvOption | None = None): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def __del__(self) -> None: ...
